# Import Libraries

In [26]:
# import libraries
import numpy as np
from numpy import median
from scipy import stats
import pandas as pd
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
%matplotlib inline
from collections import Counter
import random as rn
from functools import reduce

# Import and suppress warnings
import warnings
warnings.filterwarnings('ignore')
import os

# Import the dataset

In [27]:
# Read the file
df = pd.read_csv('Clean1.csv')

In [28]:
df

,Unnamed: 0,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,Application ID,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,...,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0,41.0,1,Travel_Rarely,1102.0,Sales,1.0,2.0,Life Sciences,1,1,123456,2.0,Female,94,3.0,2.0,Sales Executive,...,Single,5993,19479.0,7.0,Y,Yes,11,3.0,1.0,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0
1,1,41.0,1,Travel_Rarely,1102.0,Sales,1.0,2.0,Life Sciences,1,1,123458,2.0,Female,94,3.0,2.0,Sales Executive,...,Single,5993,19479.0,4.0,Y,Yes,11,3.0,1.0,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0
2,2,41.0,1,Travel_Rarely,1102.0,Sales,1.0,2.0,Life Sciences,1,7,123462,2.0,Female,94,3.0,2.0,Sales Executive,...,Single,5993,19479.0,7.0,Y,Yes,11,3.0,1.0,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0
3,3,41.0,1,Travel_Rarely,1102.0,Sales,1.0,2.0,Life Sciences,1,8,123463,2.0,Female,94,3.0,2.0,Sales Executive,...,Single,5993,19479.0,4.0,Y,Yes,11,3.0,1.0,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0
4,4,41.0,1,Travel_Rarely,1102.0,Sales,1.0,2.0,Life Sciences,1,9,123464,2.0,Female,94,3.0,2.0,Sales Executive,...,Single,5993,19479.0,7.0,Y,Yes,11,3.0,1.0,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23199,23199,60.0,0,Travel_Rarely,370.0,Research & Development,1.0,4.0,Life Sciences,1,19337,142792.0,3.0,Male,92,1.0,3.0,Healthcare Representative,...,Divorced,10883,20467.0,0.0,Y,No,20,4.0,3.0,80.0,1.0,19.0,2.0,4.0,1.0,0.0,0.0,0.0
23200,23200,60.0,0,Travel_Rarely,370.0,Research & Development,1.0,4.0,Medical,1,19338,142793.0,3.0,Male,92,1.0,3.0,Healthcare Representative,...,Divorced,10883,20467.0,3.0,Y,No,20,3.0,3.0,80.0,1.0,19.0,2.0,4.0,1.0,0.0,0.0,0.0
23201,23201,60.0,0,Travel_Rarely,370.0,Research & Development,1.0,4.0,Life Sciences,1,19340,142795.0,3.0,Male,92,1.0,3.0,Healthcare Representative,...,Divorced,10883,20467.0,0.0,Y,No,20,3.0,3.0,80.0,1.0,19.0,2.0,4.0,1.0,0.0,0.0,0.0
23202,23202,60.0,0,Travel_Rarely,370.0,Research & Development,1.0,4.0,Medical,1,19344,142799.0,3.0,Male,92,1.0,3.0,Healthcare Representative,...,Single,10883,20467.0,3.0,Y,No,20,4.0,3.0,80.0,1.0,20.0,2.0,3.0,20.0,7.0,2.0,13.0
23203,23203,60.0,0,Travel_Rarely,370.0,Research & Development,1.0,4.0,Life Sciences,1,19345,142800.0,3.0,Male,92,1.0,3.0,Healthcare Representative,...,Divorced,10883,20467.0,0.0,Y,No,20,4.0,3.0,80.0,1.0,19.0,2.0,4.0,1.0,0.0,0.0,0.0

In [29]:
column_index_to_drop = [0,11]
df = df.drop(df.columns[column_index_to_drop], axis=1)

In [30]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,1,Travel_Rarely,1102.0,Sales,1.0,2.0,Life Sciences,1,1,2.0,Female,94,3.0,2.0,Sales Executive,4,Single,5993,19479.0,7.0,Y,Yes,11,3.0,1.0,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0
1,41.0,1,Travel_Rarely,1102.0,Sales,1.0,2.0,Life Sciences,1,1,2.0,Female,94,3.0,2.0,Sales Executive,4,Single,5993,19479.0,4.0,Y,Yes,11,3.0,1.0,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0
2,41.0,1,Travel_Rarely,1102.0,Sales,1.0,2.0,Life Sciences,1,7,2.0,Female,94,3.0,2.0,Sales Executive,4,Single,5993,19479.0,7.0,Y,Yes,11,3.0,1.0,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0
3,41.0,1,Travel_Rarely,1102.0,Sales,1.0,2.0,Life Sciences,1,8,2.0,Female,94,3.0,2.0,Sales Executive,4,Single,5993,19479.0,4.0,Y,Yes,11,3.0,1.0,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0
4,41.0,1,Travel_Rarely,1102.0,Sales,1.0,2.0,Life Sciences,1,9,2.0,Female,94,3.0,2.0,Sales Executive,4,Single,5993,19479.0,7.0,Y,Yes,11,3.0,1.0,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23199,60.0,0,Travel_Rarely,370.0,Research & Development,1.0,4.0,Life Sciences,1,19337,3.0,Male,92,1.0,3.0,Healthcare Representative,4,Divorced,10883,20467.0,0.0,Y,No,20,4.0,3.0,80.0,1.0,19.0,2.0,4.0,1.0,0.0,0.0,0.0
23200,60.0,0,Travel_Rarely,370.0,Research & Development,1.0,4.0,Medical,1,19338,3.0,Male,92,1.0,3.0,Healthcare Representative,4,Divorced,10883,20467.0,3.0,Y,No,20,3.0,3.0,80.0,1.0,19.0,2.0,4.0,1.0,0.0,0.0,0.0
23201,60.0,0,Travel_Rarely,370.0,Research & Development,1.0,4.0,Life Sciences,1,19340,3.0,Male,92,1.0,3.0,Healthcare Representative,4,Divorced,10883,20467.0,0.0,Y,No,20,3.0,3.0,80.0,1.0,19.0,2.0,4.0,1.0,0.0,0.0,0.0
23202,60.0,0,Travel_Rarely,370.0,Research & Development,1.0,4.0,Medical,1,19344,3.0,Male,92,1.0,3.0,Healthcare Representative,4,Single,10883,20467.0,3.0,Y,No,20,4.0,3.0,80.0,1.0,20.0,2.0,3.0,20.0,7.0,2.0,13.0
23203,60.0,0,Travel_Rarely,370.0,Research & Development,1.0,4.0,Life Sciences,1,19345,3.0,Male,92,1.0,3.0,Healthcare Representative,4,Divorced,10883,20467.0,0.0,Y,No,20,4.0,3.0,80.0,1.0,19.0,2.0,4.0,1.0,0.0,0.0,0.0

In [31]:
df.shape

(23204, 35)

In [32]:
df.dtypes

Age                         float64
Attrition                     int64
BusinessTravel               object
DailyRate                   float64
Department                   object
DistanceFromHome            float64
Education                   float64
EducationField               object
EmployeeCount                 int64
EmployeeNumber               object
EnvironmentSatisfaction     float64
Gender                       object
HourlyRate                    int64
JobInvolvement              float64
JobLevel                    float64
JobRole                      object
JobSatisfaction               int64
MaritalStatus                object
MonthlyIncome                 int64
MonthlyRate                 float64
NumCompaniesWorked          float64
Over18                       object
OverTime                     object
PercentSalaryHike             int64
PerformanceRating           float64
RelationshipSatisfaction    float64
StandardHours               float64
StockOptionLevel            float64
TotalWorkingYears           float64
TrainingTimesLastYear       float64
WorkLifeBalance             float64
YearsAtCompany              float64
YearsInCurrentRole          float64
YearsSinceLastPromotion     float64
YearsWithCurrManager        float64
dtype: object

# Inspect all of the columns and inspect the sructure of the dataframe

In [33]:
# Set options to inspect all of the columns
pd.options.display.max_columns = 36

# Inspect the structure of the dataframe
df.sample(5).transpose()

,69,21806,1156,15789,15230
Age,41.0,55.0,37.0,33.0,33.0
Attrition,1,1,0,0,1
BusinessTravel,Travel_Rarely,Travel_Rarely,Travel_Rarely,Travel_Rarely,Travel_Rarely
DailyRate,1085.0,436.0,367.0,217.0,350.0
Department,Research & Development,Sales,Research & Development,Sales,Sales
DistanceFromHome,2.0,2.0,25.0,10.0,5.0
Education,4.0,1.0,2.0,4.0,3.0
EducationField,Life Sciences,Life Sciences,Technical Degree,Marketing,Life Sciences
EmployeeCount,1,1,1,1,1
EmployeeNumber,10720,9779,13352,12456,5886
EnvironmentSatisfaction,2.0,3.0,3.0,3.0,4.0
Gender,Female,Male,Female,Female,Female
HourlyRate,57,37,52,72,34
JobInvolvement,1.0,3.0,2.0,3.0,3.0
JobLevel,1.0,2.0,2.0,1.0,1.0
JobRole,Laboratory Technician,Sales Executive,Healthcare Representative,Sales Representative,Sales Representative
JobSatisfaction,4,4,4,4,3
MaritalStatus,Divorced,Single,Divorced,Single,Single
MonthlyIncome,2778,5160,5731,2323,2851
MonthlyRate,17725.0,21519.0,17171.0,17205.0,9150.0
NumCompaniesWorked,4.0,4.0,0.0,1.0,7.0
Over18,Y,Y,Y,Y,Y
OverTime,Yes,No,No,Yes,Yes
PercentSalaryHike,13,16,13,14,13
PerformanceRating,3.0,3.0,3.0,3.0,3.0
RelationshipSatisfaction,3.0,3.0,3.0,2.0,2.0
StandardHours,80.0,80.0,80.0,80.0,80.0
StockOptionLevel,1.0,0.0,2.0,0.0,0.0
TotalWorkingYears,10.0,12.0,9.0,2.0,1.0
TrainingTimesLastYear,1.0,3.0,2.0,3.0,2.0
WorkLifeBalance,2.0,2.0,3.0,3.0,3.0
YearsAtCompany,7.0,9.0,6.0,2.0,1.0
YearsInCurrentRole,7.0,7.0,2.0,2.0,0.0
YearsSinceLastPromotion,1.0,7.0,1.0,0.0,0.0
YearsWithCurrManager,0.0,3.0,3.0,2.0,0.0

In [34]:
df.index

RangeIndex(start=0, stop=23204, step=1)

In [35]:
df.axes

[RangeIndex(start=0, stop=23204, step=1),
 Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
        'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
        'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
        'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
        'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
        'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
        'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
        'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
        'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
        'YearsWithCurrManager'],
       dtype='object')]

In [36]:
#df.get_dtype_counts()
dtype_counts = df.dtypes.value_counts()
dtype_counts

float64    20
object      9
int64       6
Name: count, dtype: int64

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23204 entries, 0 to 23203
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       23204 non-null  float64
 1   Attrition                 23204 non-null  int64
 2   BusinessTravel            23204 non-null  object
 3   DailyRate                 23204 non-null  float64
 4   Department                23204 non-null  object
 5   DistanceFromHome          23204 non-null  float64
 6   Education                 23204 non-null  float64
 7   EducationField            23204 non-null  object
 8   EmployeeCount             23204 non-null  int64
 9   EmployeeNumber            23204 non-null  object
 10  EnvironmentSatisfaction   23204 non-null  float64
 11  Gender                    23204 non-null  object
 12  HourlyRate                23204 non-null  int64
 13  JobInvolvement            23204 non-null  float64
 14  JobLevel                  23204 non-null  float64
 15  JobRole                   23204 non-null  object
 16  JobSatisfaction           23204 non-null  int64
 17  MaritalStatus             23204 non-null  object
 18  MonthlyIncome             23204 non-null  int64
 19  MonthlyRate               23204 non-null  float64
 20  NumCompaniesWorked        23204 non-null  float64
 21  Over18                    23204 non-null  object
 22  OverTime                  23204 non-null  object
 23  PercentSalaryHike         23204 non-null  int64
 24  PerformanceRating         23204 non-null  float64
 25  RelationshipSatisfaction  23204 non-null  float64
 26  StandardHours             23204 non-null  float64
 27  StockOptionLevel          23204 non-null  float64
 28  TotalWorkingYears         23204 non-null  float64
 29  TrainingTimesLastYear     23204 non-null  float64
 30  WorkLifeBalance           23204 non-null  float64
 31  YearsAtCompany            23204 non-null  float64
 32  YearsInCurrentRole        23204 non-null  float64
 33  YearsSinceLastPromotion   23204 non-null  float64
 34  YearsWithCurrManager      23204 non-null  float64
dtypes: float64(20), int64(6), object(9)
memory usage: 6.2+ MB

# Change the data type of columns

In [38]:
df = df.apply(lambda col: col.astype(int) if col.dtype == 'float64' else col)

In [39]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,4,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
2,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,7,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
3,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,8,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,4,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
4,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,9,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23199,60,0,Travel_Rarely,370,Research & Development,1,4,Life Sciences,1,19337,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,Y,No,20,4,3,80,1,19,2,4,1,0,0,0
23200,60,0,Travel_Rarely,370,Research & Development,1,4,Medical,1,19338,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,3,Y,No,20,3,3,80,1,19,2,4,1,0,0,0
23201,60,0,Travel_Rarely,370,Research & Development,1,4,Life Sciences,1,19340,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,Y,No,20,3,3,80,1,19,2,4,1,0,0,0
23202,60,0,Travel_Rarely,370,Research & Development,1,4,Medical,1,19344,3,Male,92,1,3,Healthcare Representative,4,Single,10883,20467,3,Y,No,20,4,3,80,1,20,2,3,20,7,2,13
23203,60,0,Travel_Rarely,370,Research & Development,1,4,Life Sciences,1,19345,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,Y,No,20,4,3,80,1,19,2,4,1,0,0,0

In [40]:
#df.get_dtype_counts()
dtype_counts = df.dtypes.value_counts()
dtype_counts

int64     26
object     9
Name: count, dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23204 entries, 0 to 23203
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       23204 non-null  int64
 1   Attrition                 23204 non-null  int64
 2   BusinessTravel            23204 non-null  object
 3   DailyRate                 23204 non-null  int64
 4   Department                23204 non-null  object
 5   DistanceFromHome          23204 non-null  int64
 6   Education                 23204 non-null  int64
 7   EducationField            23204 non-null  object
 8   EmployeeCount             23204 non-null  int64
 9   EmployeeNumber            23204 non-null  object
 10  EnvironmentSatisfaction   23204 non-null  int64
 11  Gender                    23204 non-null  object
 12  HourlyRate                23204 non-null  int64
 13  JobInvolvement            23204 non-null  int64
 14  JobLevel                  23204 non-null  int64
 15  JobRole                   23204 non-null  object
 16  JobSatisfaction           23204 non-null  int64
 17  MaritalStatus             23204 non-null  object
 18  MonthlyIncome             23204 non-null  int64
 19  MonthlyRate               23204 non-null  int64
 20  NumCompaniesWorked        23204 non-null  int64
 21  Over18                    23204 non-null  object
 22  OverTime                  23204 non-null  object
 23  PercentSalaryHike         23204 non-null  int64
 24  PerformanceRating         23204 non-null  int64
 25  RelationshipSatisfaction  23204 non-null  int64
 26  StandardHours             23204 non-null  int64
 27  StockOptionLevel          23204 non-null  int64
 28  TotalWorkingYears         23204 non-null  int64
 29  TrainingTimesLastYear     23204 non-null  int64
 30  WorkLifeBalance           23204 non-null  int64
 31  YearsAtCompany            23204 non-null  int64
 32  YearsInCurrentRole        23204 non-null  int64
 33  YearsSinceLastPromotion   23204 non-null  int64
 34  YearsWithCurrManager      23204 non-null  int64
dtypes: int64(26), object(9)
memory usage: 6.2+ MB

# Description about the dataset

In [42]:
df.describe(include="all")

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,23204.00000,23204.000000,23204,23204.000000,23204,23204.000000,23204.000000,23204,23204.0,23204,23204.000000,23204,23204.000000,23204.000000,23204.000000,23204,23204.000000,23204,23204.000000,23204.000000,23204.000000,23204,23204,23204.000000,23204.000000,23204.000000,23204.0,23204.000000,23204.000000,23204.000000,23204.000000,23204.000000,23204.000000,23204.000000,23204.000000
unique,NaN,NaN,3,NaN,3,NaN,NaN,7,NaN,23141,NaN,2,NaN,NaN,NaN,9,NaN,3,NaN,NaN,NaN,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Travel_Rarely,NaN,Research & Development,NaN,NaN,Life Sciences,NaN,1,NaN,Male,NaN,NaN,NaN,Sales Executive,NaN,Married,NaN,NaN,NaN,Y,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,16457,NaN,15132,NaN,NaN,9578,NaN,6,NaN,13914,NaN,NaN,NaN,5064,NaN,10613,NaN,NaN,NaN,23204,16633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,36.91954,0.158335,NaN,802.328349,NaN,9.190355,2.908723,NaN,1.0,NaN,2.719057,NaN,65.849853,2.632693,2.065032,NaN,2.728237,NaN,6506.478667,14303.508533,2.585546,NaN,NaN,15.213024,3.155232,2.713067,80.0,0.793958,11.265127,2.797793,2.760903,7.014825,4.229185,2.180874,4.129805
std,9.11660,0.365062,NaN,403.193041,NaN,8.099525,1.024811,NaN,0.0,NaN,1.095208,NaN,20.338868,0.587639,1.105769,NaN,1.101344,NaN,4705.527434,7099.381683,2.272585,NaN,NaN,3.660058,0.362133,1.080830,0.0,0.850652,7.765663,1.290553,0.705886,6.137174,3.626636,3.215231,3.571334
min,18.00000,0.000000,NaN,102.000000,NaN,1.000000,1.000000,NaN,1.0,NaN,1.000000,NaN,30.000000,1.000000,1.000000,NaN,1.000000,NaN,1009.000000,2094.000000,0.000000,NaN,NaN,11.000000,3.000000,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.00000,0.000000,NaN,465.000000,NaN,2.000000,2.000000,NaN,1.0,NaN,2.000000,NaN,48.000000,2.000000,1.000000,NaN,2.000000,NaN,2911.000000,8053.000000,1.000000,NaN,NaN,12.000000,3.000000,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.00000,0.000000,NaN,802.000000,NaN,7.000000,3.000000,NaN,1.0,NaN,3.000000,NaN,66.000000,3.000000,2.000000,NaN,3.000000,NaN,4936.000000,14222.000000,2.000000,NaN,NaN,14.000000,3.000000,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.00000,0.000000,NaN,1157.000000,NaN,14.000000,4.000000,NaN,1.0,NaN,4.000000,NaN,83.000000,3.000000,3.000000,NaN,4.000000,NaN,8380.000000,20460.000000,4.000000,NaN,NaN,18.000000,3.000000,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,10.000000,7.000000,3.000000,7.000000
max,60.00000,1.000000,NaN,1499.000000,NaN,29.000000,5.000000,NaN,1.0,NaN,4.000000,NaN,100.000000,3.000000,5.000000,NaN,4.000000,NaN,19999.000000,26999.000000,7.000000,NaN,NaN,25.000000,4.000000,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

# Check weirdness on the dataset by looking some features

In [43]:
df['TotalWorkingYears'][df['TotalWorkingYears'] < 0].sum()

0

In [44]:
df['MaritalStatus'].unique()

array(['Single', 'Divorced', 'Married'], dtype=object)

In [45]:
df['YearsAtCompany'][df['YearsAtCompany'] > 41].sum()

0

# **Check for missing values**

In [46]:
# Check for missing values
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

# Check for duplicate observations and remove them from the dataset

In [47]:
# Check for duplicate observations
df.duplicated().sum()

15

In [48]:
duplicate_rows = df[df.duplicated()]
print("\nDuplicate Rows:")
print(duplicate_rows)

Duplicate Rows:
       Age  Attrition BusinessTravel  DailyRate              Department  \
10      41          1  Travel_Rarely       1102                   Sales
11      41          1  Travel_Rarely       1102                   Sales
12      41          1  Travel_Rarely       1102                   Sales
660     37          1  Travel_Rarely        807         Human Resources
661     37          1  Travel_Rarely        807         Human Resources
662     37          1  Travel_Rarely        807         Human Resources
663     37          1  Travel_Rarely        807         Human Resources
6062    26          1  Travel_Rarely       1357  Research & Development
6063    26          1  Travel_Rarely       1357  Research & Development
6064    26          1  Travel_Rarely       1357  Research & Development
6065    26          1  Travel_Rarely       1357  Research & Development
11714   32          0     Non-Travel        953  Research & Development
17355   21          0  Travel_Rarely        391  Research & Development
17356   21          0  Travel_Rarely        391  Research & Development
17357   21          0  Travel_Rarely        391  Research & Development

       DistanceFromHome  Education    EducationField  EmployeeCount  \
10                    1          2     Life Sciences              1
11                    1          2     Life Sciences              1
12                    1          2     Life Sciences              1
660                   6          4   Human Resources              1
661                   6          4         Marketing              1
662                   6          4   Human Resources              1
663                   6          4         Marketing              1
6062                 25          3     Life Sciences              1
6063                 25          3  Technical Degree              1
6064                 25          3     Life Sciences              1
6065                 25          3  Technical Degree              1
11714                 5          4     Life Sciences              1
17355                15          2     Life Sciences              1
17356                15          2           Medical              1
17357                15          2     Life Sciences              1

      EmployeeNumber  EnvironmentSatisfaction  Gender  HourlyRate  \
10                 1                        2  Female          94
11                 1                        2  Female          94
12                 7                        2  Female          94
660                1                        1  Female          37
661                4                        1  Female          37
662                5                        1  Female          37
663                6                        1  Female          37
6062             813                        1    Male          48
6063             814                        1    Male          48
6064             815                        1    Male          48
6065             818                        1    Male          48
11714          23244                        4  Female         100
17355            816                        1    Male          39
17356            817                        1    Male          39
17357            819                        3    Male          39

       JobInvolvement  JobLevel                JobRole  JobSatisfaction  \
10                  3         2        Sales Executive                4
11                  3         2        Sales Executive                4
12                  3         2        Sales Executive                4
660                 3         2        Sales Executive                4
661                 3         2        Sales Executive                4
662                 3         2        Sales Executive                4
663                 3         2        Sales Executive                4
6062                1         1  Laboratory Technician                3
6063                1         1  Laboratory Technician                3
6064                1         1  Laboratory Technician                3
6065                1         1  Laboratory Technician                3
11714               2         2        Sales Executive                4
17355               1         1  Laboratory Technician                3
17356               1         1  Laboratory Technician                3
17357               1         1  Laboratory Technician                3

      MaritalStatus  MonthlyIncome  MonthlyRate  NumCompaniesWorked Over18  \
10           Single           5993        19479                   7      Y
11           Single           5993        19479                   4      Y
12           Single           5993        19479                   7      Y
660          Single           5993        19479                   7      Y
661          Single           5993        19479                   5      Y
662          Single           5993        19479                   7      Y
663          Single           5993        19479                   5      Y
6062         Single           2293        21534                   1      Y
6063         Single           2293        26009                   1      Y
6064         Single           2293        10558                   1      Y
6065         Single           2293        10558                   1      Y
11714       Married           6652        14369                   5      Y
17355        Single           2293        10558                   1      Y
17356        Single           2293        10558                   1      Y
17357        Single           2293         7324                   1      Y

      OverTime  PercentSalaryHike  PerformanceRating  \
10         Yes                 11                  3
11         Yes                 11                  3
12         Yes                 11                  3
660        Yes                 11                  4
661        Yes                 11                  3
662        Yes                 11                  3
663        Yes                 11                  3
6062        No                 12                  3
6063        No                 12                  3
6064        No                 12                  3
6065        No                 12                  3
11714       No                 13                  3
17355       No                 12                  4
17356       No                 12                  3
17357       No                 12                  3

       RelationshipSatisfaction  StandardHours  StockOptionLevel  \
10                            1             80                 0
11                            1             80                 0
12                            1             80                 0
660                           1             80                 0
661                           1             80                 0
662                           1             80                 0
663                           1             80                 0
6062                          3             80                 0
6063                          3             80                 0
6064                          3             80                 0
6065                          3             80                 0
11714                         1             80                 1
17355                         3             80                 0
17356                         3             80                 0
17357                         3             80                 0

       TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
10                     8                      0                1
11                     8                      0                1
12                     8                      0                1
660                    8                      0                1
661                    8                      0                1
662                    8                      0                1
663                    8                      0                1
6062                   1                      2                2
6063                   1                      2                2
6064                   1                      2                2
6065                   1                      2                2
11714                  8                      2                2
17355                  1                      2                2
17356                  1                      2                2
17357                  1                      2                2

       YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
10                  6                   4                        0
11                  6                   4                        0
12                  6                   4                        0
660                 6                   4                        0
661                 6                   4                        0
662                 6                   4                        0
663                 6                   4                        0
6062                1                   0                        0
6063                1                   0                        0
6064                1                   0                        0
6065                1                   0                        0
11714               6                   3                        0
17355               1                   0                        0
17356               1                   0                        0
17357               1                   0                        0

       YearsWithCurrManager
10                        5
11                        5
12                        5
660                       5
661                       5
662                       5
663                       5
6062                      1
6063                      1
6064                      1
6065                      1
11714                     0
17355                     1
17356                     1
17357                     1

In [49]:
duplicates = df.duplicated()
print("\nDuplicate Rows (True indicates duplicate):")
print(duplicates)

# Drop duplicate rows
df1 = df.drop_duplicates()

print("\nDataFrame After Dropping Duplicates:")
print(df1)

Duplicate Rows (True indicates duplicate):
0        False
1        False
2        False
3        False
4        False
         ...
23199    False
23200    False
23201    False
23202    False
23203    False
Length: 23204, dtype: bool

DataFrame After Dropping Duplicates:
       Age  Attrition BusinessTravel  DailyRate              Department  \
0       41          1  Travel_Rarely       1102                   Sales
1       41          1  Travel_Rarely       1102                   Sales
2       41          1  Travel_Rarely       1102                   Sales
3       41          1  Travel_Rarely       1102                   Sales
4       41          1  Travel_Rarely       1102                   Sales
...    ...        ...            ...        ...                     ...
23199   60          0  Travel_Rarely        370  Research & Development
23200   60          0  Travel_Rarely        370  Research & Development
23201   60          0  Travel_Rarely        370  Research & Development
23202   60          0  Travel_Rarely        370  Research & Development
23203   60          0  Travel_Rarely        370  Research & Development

       DistanceFromHome  Education EducationField  EmployeeCount  \
0                     1          2  Life Sciences              1
1                     1          2  Life Sciences              1
2                     1          2  Life Sciences              1
3                     1          2  Life Sciences              1
4                     1          2  Life Sciences              1
...                 ...        ...            ...            ...
23199                 1          4  Life Sciences              1
23200                 1          4        Medical              1
23201                 1          4  Life Sciences              1
23202                 1          4        Medical              1
23203                 1          4  Life Sciences              1

      EmployeeNumber  EnvironmentSatisfaction  Gender  HourlyRate  \
0                  1                        2  Female          94
1                  1                        2  Female          94
2                  7                        2  Female          94
3                  8                        2  Female          94
4                  9                        2  Female          94
...              ...                      ...     ...         ...
23199          19337                        3    Male          92
23200          19338                        3    Male          92
23201          19340                        3    Male          92
23202          19344                        3    Male          92
23203          19345                        3    Male          92

       JobInvolvement  JobLevel                    JobRole  JobSatisfaction  \
0                   3         2            Sales Executive                4
1                   3         2            Sales Executive                4
2                   3         2            Sales Executive                4
3                   3         2            Sales Executive                4
4                   3         2            Sales Executive                4
...               ...       ...                        ...              ...
23199               1         3  Healthcare Representative                4
23200               1         3  Healthcare Representative                4
23201               1         3  Healthcare Representative                4
23202               1         3  Healthcare Representative                4
23203               1         3  Healthcare Representative                4

      MaritalStatus  MonthlyIncome  MonthlyRate  NumCompaniesWorked Over18  \
0            Single           5993        19479                   7      Y
1            Single           5993        19479                   4      Y
2            Single           5993        19479                   7      Y
3            Single           5993        19479                   4      Y
4            Single           5993        19479                   7      Y
...             ...            ...          ...                 ...    ...
23199      Divorced          10883        20467                   0      Y
23200      Divorced          10883        20467                   3      Y
23201      Divorced          10883        20467                   0      Y
23202        Single          10883        20467                   3      Y
23203      Divorced          10883        20467                   0      Y

      OverTime  PercentSalaryHike  PerformanceRating  \
0          Yes                 11                  3
1          Yes                 11                  3
2          Yes                 11                  3
3          Yes                 11                  3
4          Yes                 11                  3
...        ...                ...                ...
23199       No                 20                  4
23200       No                 20                  3
23201       No                 20                  3
23202       No                 20                  4
23203       No                 20                  4

       RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                             1             80                 0
1                             1             80                 0
2                             1             80                 0
3                             1             80                 0
4                             1             80                 0
...                         ...            ...               ...
23199                         3             80                 1
23200                         3             80                 1
23201                         3             80                 1
23202                         3             80                 1
23203                         3             80                 1

       TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0                      8                      0                1
1                      8                      0                1
2                      8                      0                1
3                      8                      0                1
4                      8                      0                1
...                  ...                    ...              ...
23199                 19                      2                4
23200                 19                      2                4
23201                 19                      2                4
23202                 20                      2                3
23203                 19                      2                4

       YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0                   6                   4                        0
1                   6                   4                        0
2                   6                   4                        0
3                   6                   4                        0
4                   6                   4                        0
...               ...                 ...                      ...
23199               1                   0                        0
23200               1                   0                        0
23201               1                   0                        0
23202              20                   7                        2
23203               1                   0                        0

       YearsWithCurrManager
0                         5
1                         5
2                         5
3                         5
4                         5
...                     ...
23199                     0
23200                     0
23201                     0
23202                    13
23203                     0

[23189 rows x 35 columns]

In [50]:
df1

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,4,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
2,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,7,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
3,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,8,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,4,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
4,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,9,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23199,60,0,Travel_Rarely,370,Research & Development,1,4,Life Sciences,1,19337,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,Y,No,20,4,3,80,1,19,2,4,1,0,0,0
23200,60,0,Travel_Rarely,370,Research & Development,1,4,Medical,1,19338,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,3,Y,No,20,3,3,80,1,19,2,4,1,0,0,0
23201,60,0,Travel_Rarely,370,Research & Development,1,4,Life Sciences,1,19340,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,Y,No,20,3,3,80,1,19,2,4,1,0,0,0
23202,60,0,Travel_Rarely,370,Research & Development,1,4,Medical,1,19344,3,Male,92,1,3,Healthcare Representative,4,Single,10883,20467,3,Y,No,20,4,3,80,1,20,2,3,20,7,2,13
23203,60,0,Travel_Rarely,370,Research & Development,1,4,Life Sciences,1,19345,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,Y,No,20,4,3,80,1,19,2,4,1,0,0,0

In [51]:
df1.duplicated().sum()

0

In [52]:
df1.nunique().sort_values()

Over18                          1
StandardHours                   1
EmployeeCount                   1
Gender                          2
Attrition                       2
PerformanceRating               2
OverTime                        2
JobInvolvement                  3
MaritalStatus                   3
Department                      3
BusinessTravel                  3
StockOptionLevel                4
EnvironmentSatisfaction         4
JobSatisfaction                 4
RelationshipSatisfaction        4
WorkLifeBalance                 4
Education                       5
JobLevel                        5
TrainingTimesLastYear           7
EducationField                  7
NumCompaniesWorked              8
JobRole                         9
PercentSalaryHike              15
YearsSinceLastPromotion        16
YearsWithCurrManager           18
YearsInCurrentRole             19
DistanceFromHome               29
YearsAtCompany                 37
TotalWorkingYears              40
Age                            43
HourlyRate                     71
DailyRate                     883
MonthlyIncome                1349
MonthlyRate                  1427
EmployeeNumber              23141
dtype: int64

In [53]:
df3 = df1.drop_duplicates(subset="EmployeeNumber", keep="first")

df3

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
2,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,7,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
3,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,8,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,4,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
4,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,9,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
5,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,10,4,Female,33,3,4,Manager,3,Divorced,14756,19730,2,Y,Yes,14,3,3,80,3,21,2,3,5,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23199,60,0,Travel_Rarely,370,Research & Development,1,4,Life Sciences,1,19337,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,Y,No,20,4,3,80,1,19,2,4,1,0,0,0
23200,60,0,Travel_Rarely,370,Research & Development,1,4,Medical,1,19338,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,3,Y,No,20,3,3,80,1,19,2,4,1,0,0,0
23201,60,0,Travel_Rarely,370,Research & Development,1,4,Life Sciences,1,19340,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,Y,No,20,3,3,80,1,19,2,4,1,0,0,0
23202,60,0,Travel_Rarely,370,Research & Development,1,4,Medical,1,19344,3,Male,92,1,3,Healthcare Representative,4,Single,10883,20467,3,Y,No,20,4,3,80,1,20,2,3,20,7,2,13
23203,60,0,Travel_Rarely,370,Research & Development,1,4,Life Sciences,1,19345,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,Y,No,20,4,3,80,1,19,2,4,1,0,0,0

In [54]:
df3.nunique().sort_values()

Over18                          1
StandardHours                   1
EmployeeCount                   1
Gender                          2
Attrition                       2
PerformanceRating               2
OverTime                        2
JobInvolvement                  3
MaritalStatus                   3
Department                      3
BusinessTravel                  3
StockOptionLevel                4
EnvironmentSatisfaction         4
JobSatisfaction                 4
RelationshipSatisfaction        4
WorkLifeBalance                 4
Education                       5
JobLevel                        5
TrainingTimesLastYear           7
EducationField                  7
NumCompaniesWorked              8
JobRole                         9
PercentSalaryHike              15
YearsSinceLastPromotion        16
YearsWithCurrManager           18
YearsInCurrentRole             19
DistanceFromHome               29
YearsAtCompany                 37
TotalWorkingYears              40
Age                            43
HourlyRate                     71
DailyRate                     883
MonthlyIncome                1349
MonthlyRate                  1427
EmployeeNumber              23141
dtype: int64

# Drop useless fetures and rename the dataframe

In [55]:
df2 = df3.drop(labels = ['Over18','StandardHours','EmployeeCount'], axis = 1)

# Moving Response Variable to the last column

In [56]:
# Moving Response Variable to the last column
front = df2['Attrition']
df2.drop(labels=['Attrition'], axis=1,inplace=True)
df2.insert(31,'Attrition',front)
df2.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Yes,11,3,1,0,8,0,1,6,4,0,5,1
2,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,7,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Yes,11,3,1,0,8,0,1,6,4,0,5,1
3,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,8,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,4,Yes,11,3,1,0,8,0,1,6,4,0,5,1
4,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,9,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Yes,11,3,1,0,8,0,1,6,4,0,5,1
5,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,10,4,Female,33,3,4,Manager,3,Divorced,14756,19730,2,Yes,14,3,3,3,21,2,3,5,0,0,2,1

# Changing object types to categories

In [57]:
# Changing object types to categories
cols = ['BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','OverTime']
for col in cols:
    df2[col] = df2[col].astype('category')

In [58]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23141 entries, 0 to 23203
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       23141 non-null  int64
 1   BusinessTravel            23141 non-null  category
 2   DailyRate                 23141 non-null  int64
 3   Department                23141 non-null  category
 4   DistanceFromHome          23141 non-null  int64
 5   Education                 23141 non-null  int64
 6   EducationField            23141 non-null  category
 7   EmployeeNumber            23141 non-null  object
 8   EnvironmentSatisfaction   23141 non-null  int64
 9   Gender                    23141 non-null  category
 10  HourlyRate                23141 non-null  int64
 11  JobInvolvement            23141 non-null  int64
 12  JobLevel                  23141 non-null  int64
 13  JobRole                   23141 non-null  category
 14  JobSatisfaction           23141 non-null  int64
 15  MaritalStatus             23141 non-null  category
 16  MonthlyIncome             23141 non-null  int64
 17  MonthlyRate               23141 non-null  int64
 18  NumCompaniesWorked        23141 non-null  int64
 19  OverTime                  23141 non-null  category
 20  PercentSalaryHike         23141 non-null  int64
 21  PerformanceRating         23141 non-null  int64
 22  RelationshipSatisfaction  23141 non-null  int64
 23  StockOptionLevel          23141 non-null  int64
 24  TotalWorkingYears         23141 non-null  int64
 25  TrainingTimesLastYear     23141 non-null  int64
 26  WorkLifeBalance           23141 non-null  int64
 27  YearsAtCompany            23141 non-null  int64
 28  YearsInCurrentRole        23141 non-null  int64
 29  YearsSinceLastPromotion   23141 non-null  int64
 30  YearsWithCurrManager      23141 non-null  int64
 31  Attrition                 23141 non-null  int64
dtypes: category(7), int64(24), object(1)
memory usage: 4.7+ MB

In [59]:
df2["EmployeeNumber"].dtype

dtype('O')

In [60]:
# Convert column 'A' to int
#df2["EmployeeNumber"] = df2["EmployeeNumber"].astype(int)
# Convert column 'A' to int, handling non-numeric values
df2["EmployeeNumber"] = pd.to_numeric(df2["EmployeeNumber"], errors="coerce")  # Convert invalid values to NaN
df2["EmployeeNumber"] = df2["EmployeeNumber"].fillna(0).astype(int)  # Replace NaN with 0 and convert to int

df2

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Yes,11,3,1,0,8,0,1,6,4,0,5,1
2,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,7,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Yes,11,3,1,0,8,0,1,6,4,0,5,1
3,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,8,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,4,Yes,11,3,1,0,8,0,1,6,4,0,5,1
4,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,9,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Yes,11,3,1,0,8,0,1,6,4,0,5,1
5,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,10,4,Female,33,3,4,Manager,3,Divorced,14756,19730,2,Yes,14,3,3,3,21,2,3,5,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23199,60,Travel_Rarely,370,Research & Development,1,4,Life Sciences,19337,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,No,20,4,3,1,19,2,4,1,0,0,0,0
23200,60,Travel_Rarely,370,Research & Development,1,4,Medical,19338,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,3,No,20,3,3,1,19,2,4,1,0,0,0,0
23201,60,Travel_Rarely,370,Research & Development,1,4,Life Sciences,19340,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,No,20,3,3,1,19,2,4,1,0,0,0,0
23202,60,Travel_Rarely,370,Research & Development,1,4,Medical,19344,3,Male,92,1,3,Healthcare Representative,4,Single,10883,20467,3,No,20,4,3,1,20,2,3,20,7,2,13,0
23203,60,Travel_Rarely,370,Research & Development,1,4,Life Sciences,19345,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,No,20,4,3,1,19,2,4,1,0,0,0,0

In [61]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23141 entries, 0 to 23203
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       23141 non-null  int64
 1   BusinessTravel            23141 non-null  category
 2   DailyRate                 23141 non-null  int64
 3   Department                23141 non-null  category
 4   DistanceFromHome          23141 non-null  int64
 5   Education                 23141 non-null  int64
 6   EducationField            23141 non-null  category
 7   EmployeeNumber            23141 non-null  int64
 8   EnvironmentSatisfaction   23141 non-null  int64
 9   Gender                    23141 non-null  category
 10  HourlyRate                23141 non-null  int64
 11  JobInvolvement            23141 non-null  int64
 12  JobLevel                  23141 non-null  int64
 13  JobRole                   23141 non-null  category
 14  JobSatisfaction           23141 non-null  int64
 15  MaritalStatus             23141 non-null  category
 16  MonthlyIncome             23141 non-null  int64
 17  MonthlyRate               23141 non-null  int64
 18  NumCompaniesWorked        23141 non-null  int64
 19  OverTime                  23141 non-null  category
 20  PercentSalaryHike         23141 non-null  int64
 21  PerformanceRating         23141 non-null  int64
 22  RelationshipSatisfaction  23141 non-null  int64
 23  StockOptionLevel          23141 non-null  int64
 24  TotalWorkingYears         23141 non-null  int64
 25  TrainingTimesLastYear     23141 non-null  int64
 26  WorkLifeBalance           23141 non-null  int64
 27  YearsAtCompany            23141 non-null  int64
 28  YearsInCurrentRole        23141 non-null  int64
 29  YearsSinceLastPromotion   23141 non-null  int64
 30  YearsWithCurrManager      23141 non-null  int64
 31  Attrition                 23141 non-null  int64
dtypes: category(7), int64(25)
memory usage: 4.7 MB

In [62]:
df2.nunique().sort_values()

Attrition                       2
PerformanceRating               2
OverTime                        2
Gender                          2
JobInvolvement                  3
MaritalStatus                   3
Department                      3
BusinessTravel                  3
WorkLifeBalance                 4
EnvironmentSatisfaction         4
StockOptionLevel                4
RelationshipSatisfaction        4
JobSatisfaction                 4
JobLevel                        5
Education                       5
EducationField                  7
TrainingTimesLastYear           7
NumCompaniesWorked              8
JobRole                         9
PercentSalaryHike              15
YearsSinceLastPromotion        16
YearsWithCurrManager           18
YearsInCurrentRole             19
DistanceFromHome               29
YearsAtCompany                 37
TotalWorkingYears              40
Age                            43
HourlyRate                     71
DailyRate                     883
MonthlyIncome                1349
MonthlyRate                  1427
EmployeeNumber              23140
dtype: int64

In [63]:
df2.shape

(23141, 32)

In [64]:
df2 = df2.drop_duplicates(subset="EmployeeNumber", keep="first")

df2

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Yes,11,3,1,0,8,0,1,6,4,0,5,1
2,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,7,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Yes,11,3,1,0,8,0,1,6,4,0,5,1
3,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,8,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,4,Yes,11,3,1,0,8,0,1,6,4,0,5,1
4,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,9,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,7,Yes,11,3,1,0,8,0,1,6,4,0,5,1
5,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,10,4,Female,33,3,4,Manager,3,Divorced,14756,19730,2,Yes,14,3,3,3,21,2,3,5,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23199,60,Travel_Rarely,370,Research & Development,1,4,Life Sciences,19337,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,No,20,4,3,1,19,2,4,1,0,0,0,0
23200,60,Travel_Rarely,370,Research & Development,1,4,Medical,19338,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,3,No,20,3,3,1,19,2,4,1,0,0,0,0
23201,60,Travel_Rarely,370,Research & Development,1,4,Life Sciences,19340,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,No,20,3,3,1,19,2,4,1,0,0,0,0
23202,60,Travel_Rarely,370,Research & Development,1,4,Medical,19344,3,Male,92,1,3,Healthcare Representative,4,Single,10883,20467,3,No,20,4,3,1,20,2,3,20,7,2,13,0
23203,60,Travel_Rarely,370,Research & Development,1,4,Life Sciences,19345,3,Male,92,1,3,Healthcare Representative,4,Divorced,10883,20467,0,No,20,4,3,1,19,2,4,1,0,0,0,0

# Inspect the values of categorical columns

In [65]:
df2[cols].nunique()

BusinessTravel    3
Department        3
EducationField    7
Gender            2
JobRole           9
MaritalStatus     3
OverTime          2
dtype: int64

In [66]:
for col in cols:
    display(df2[col].value_counts())

BusinessTravel
Travel_Rarely        16411
Travel_Frequently     4367
Non-Travel            2362
Name: count, dtype: int64

Department
Research & Development    15098
Sales                      7039
Human Resources            1003
Name: count, dtype: int64

EducationField
Life Sciences       9550
Medical             7285
Marketing           2519
Technical Degree    2047
Other               1302
Human Resources      436
Test                   1
Name: count, dtype: int64

Gender
Male      13883
Female     9257
Name: count, dtype: int64

JobRole
Sales Executive              5036
Research Scientist           4580
Laboratory Technician        4097
Manufacturing Director       2357
Healthcare Representative    2073
Manager                      1584
Sales Representative         1299
Research Director            1279
Human Resources               835
Name: count, dtype: int64

MaritalStatus
Married     10590
Single       7397
Divorced     5153
Name: count, dtype: int64

OverTime
No     16591
Yes     6549
Name: count, dtype: int64

In [67]:
# Get the index of rows to drop
row_index_to_drop = df2.index[df2["EducationField"] == "Test"]

# Drop the row(s)
df2 = df2.drop(row_index_to_drop)

In [68]:
for col in cols:
    display(df2[col].value_counts())

BusinessTravel
Travel_Rarely        16410
Travel_Frequently     4367
Non-Travel            2362
Name: count, dtype: int64

Department
Research & Development    15097
Sales                      7039
Human Resources            1003
Name: count, dtype: int64

EducationField
Life Sciences       9550
Medical             7285
Marketing           2519
Technical Degree    2047
Other               1302
Human Resources      436
Test                   0
Name: count, dtype: int64

Gender
Male      13882
Female     9257
Name: count, dtype: int64

JobRole
Sales Executive              5036
Research Scientist           4580
Laboratory Technician        4097
Manufacturing Director       2357
Healthcare Representative    2072
Manager                      1584
Sales Representative         1299
Research Director            1279
Human Resources               835
Name: count, dtype: int64

MaritalStatus
Married     10589
Single       7397
Divorced     5153
Name: count, dtype: int64

OverTime
No     16590
Yes     6549
Name: count, dtype: int64

In [69]:
df2.nunique().sort_values()

Attrition                       2
PerformanceRating               2
OverTime                        2
Gender                          2
JobInvolvement                  3
MaritalStatus                   3
Department                      3
BusinessTravel                  3
WorkLifeBalance                 4
EnvironmentSatisfaction         4
StockOptionLevel                4
RelationshipSatisfaction        4
JobSatisfaction                 4
JobLevel                        5
Education                       5
EducationField                  6
TrainingTimesLastYear           7
NumCompaniesWorked              8
JobRole                         9
PercentSalaryHike              15
YearsSinceLastPromotion        16
YearsWithCurrManager           18
YearsInCurrentRole             19
DistanceFromHome               29
YearsAtCompany                 37
TotalWorkingYears              40
Age                            43
HourlyRate                     71
DailyRate                     883
MonthlyIncome                1349
MonthlyRate                  1427
EmployeeNumber              23139
dtype: int64